library(data.table)
data <- fread("household_power_consumption.txt")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data1 <- subset(data, Date=="2007-02-01" | Date=="2007-02-02")
data1$Global_active_power <- as.numeric(data1$Global_active_power)
png(file="plot1.png", width = 480, height = 480)
hist(data1$Global_active_power, col = "red", main = "Global Active Power", xlab="Global Active Power(kilowatts)")
dev.off()
